repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks: # general hooks
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: name-tests-test
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ['-c', 'pyproject.toml', '-r', '.']
        additional_dependencies: ['bandit[toml]']

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks: # code formatter
      - id: black
        args: ['--config', './pyproject.toml', '.']

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks: # imports sorting
      - id: isort
        args: ['--settings-file', './pyproject.toml', '.']

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0 # linter
    hooks:
      - id: flake8

  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0 # docstring coverage
    hooks:
      - id: interrogate
        args: ['--quiet', '--fail-under=95']

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.6.0 # conventional commits
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.1
    hooks:
      - id: python-safety-dependencies-check
        files: pyproject.toml

  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 1.1.0 # sync pre-commit-config.yaml with pyproject.toml
    hooks:
      - id: sync_with_poetry
